const CARGOS = [
  ['F', 'AUXILIAR DE LIMPEZA'],
  ['ASSIST ADMINISTRATIVO I', 'ASSISTENTE ADMINISTRATIVO I'],
  ['ASSIST  ADMINISTRATIVO', 'ASSISTENTE ADMINISTRATIVO'],
  ['ASSIT ADMINISTRATIVO', 'ASSISTENTE ADMINISTRATIVO'],
  ['ASSIST CONTABIL', 'ASSISTENTE CONTÁBIL'],
  ['ASSIST DE ALMOXARIFADO', 'ASSISTENTE DE ALMOXARIFADO'],
  ['ASSIST DE COMPRAS', 'ASSISTENTE DE COMPRAS'],
  ['ASSIST DE COMPRAS II', 'ASSISTENTE DE COMPRAS II'],
  ['ASSIST DE CONTAS A RECEBER I', 'ASSISTENTE DE CONTAS A RECEBER I'],
  ['ASSIST DE DEPARTAMENTO PESSOAL', 'ASSISTENTE DE DEPARTAMENTO PESSOAL'],
  ['ASSISTENTE DE DEPTO PESSOAL', 'ASSISTENTE DE DEPARTAMENTO PESSOAL'],
  ['ASSIST DE FATURAMENTO', 'ASSISTENTE DE FATURAMENTO'],
  ['ASSIST DE FATURAMENTO II', 'ASSISTENTE DE FATURAMENTO II'],
  ['ASSIST DE FATURAMENTO III', 'ASSISTENTE DE FATURAMENTO III'],
  ['ASSIST FINANCEIRO', 'ASSISTENTE FINANCEIRO'],
  ['ASSIST DE RECURSOS HUMANOS', 'ASSISTENTE DE RECURSOS HUMANOS'],
  ['AUX SERV GERAIS', 'AUXILIAR DE SERVIÇOS GERAIS'],
  ['AUXILIAR ADMINISTRATIVO JUNIOR', 'AUXILIAR ADMINISTRATIVO JR'],
  ['AUXILIAR DE DEPTO PESSOAL', 'AUXILIAR DE DEPARTAMENTO PESSOAL'],
  ['ANALISTA CONTABIL', 'ANALISTA CONTÁBIL'],
  ['TECN DE LOGISTICA', 'TÉCNICO(A) DE LOGÍSTICA'],
  ['TÉC. EM REDES', 'TÉCNICO(A) EM REDES'],
  ['SUPERVISOR SEG. TRABALHO', 'SUPERVISOR(A) DE SEGURANÇA DO TRABALHO'],
  ['COORD DE RECEPCAO', 'COORDENADOR(A) DE RECEPÇÃO'],
  ['COORD EXPERIENCIA DO PACIENTE', 'COORDENADOR(A) DE EXPERIÊNCIA DO PACIENTE'],
  ['COORD HOTELARIA HOSPITALAR', 'COORDENADOR(A) DE HOTELARIA HOSPITALAR'],
  ['TÉC EM MANUTENÇÃO DE EQUIPAMEN', 'TÉCNICO(A) EM MANUTENÇÃO DE EQUIPAMENTOS'],
  ['TEC EQUIPAMENTOS MED HOSPITALAR', 'TÉCNICO(A) EM EQUIPAMENTOS MÉDICO-HOSPITALARES'],
  ['TECNICO EM SEGURANCA DO TRABAL', 'TÉCNICO(A) EM SEGURANÇA DO TRABALHO'],
  ['TECNICO(A) EM ANALISES CLINICA', 'TÉCNICO(A) EM ANÁLISES CLÍNICAS'],
  ['TECNICO EM ANALISES CLINICAS', 'TÉCNICO(A) EM ANÁLISES CLÍNICAS'],
  ['ASSISTENTE DE HOTELARIA HOSPIT', 'ASSISTENTE DE HOTELARIA HOSPITALAR'],
  ['FARMACEUTICA', 'FARMACÊUTICO(A)'],
  ['FARMACEUTICO COORDENADOR', 'FARMACÊUTICO(A) COORDENADOR(A)'],
  ['FARMACEUTICA ONCOLOGICA', 'FARMACÊUTICO(A) ONCOLÓGICO(A)'],
  ['BIOMEDICO(A)', 'BIOMÉDICO(A)'],
  ['BIOMEDICO(A) COORD', 'BIOMÉDICO(A) COORDENADOR(A)'],
  ['ENFERMEIRA', 'ENFERMEIRO(A)'],
  ['ENFERMEIRO', 'ENFERMEIRO(A)'],
  ['ENFERMEIRA (O) I', 'ENFERMEIRO(A) I'],
  ['ENFERMEIRA DA QUALIDADE', 'ENFERMEIRO(A) DA QUALIDADE'],
  ['ENFERMEIRO (O) EDUC CONTINUADA', 'ENFERMEIRO(A) DE EDUCAÇÃO CONTINUADA'],
  ['TECNICA DE ENFERMAGEM', 'TÉCNICO(A) DE ENFERMAGEM'],
  ['TECNICO(A) DE ENFERMAGEM', 'TÉCNICO(A) DE ENFERMAGEM'],
  ['TECNICO(A) DE FARMACIA', 'TÉCNICO(A) DE FARMÁCIA'],
  ['TECNICA DE FARMACIA', 'TÉCNICO(A) DE FARMÁCIA'],
  ['TECNICO EM FARMACIA', 'TÉCNICO(A) DE FARMÁCIA'],
  ['TECNICO(A) DE IMOB. ORTOPEDICA', 'TÉCNICO(A) DE IMOBILIZAÇÃO ORTOPÉDICA'],
  ['COPEIRA', 'COPEIRO(A)'],
  ['COPEIRA(O)', 'COPEIRO(A)'],
  ['COPEIRA ADMINISTRATIVA', 'COPEIRO(A) ADMINISTRATIVO(A)'],
  ['COSTUREIRA', 'COSTUREIRO(A)'],
  ['ENCARREGADA DE FATURAMENTO', 'ENCARREGADO(A) DE FATURAMENTO'],
  ['GERENTE ADMINISTRATIVO', 'GERENTE ADMINISTRATIVO(A)'],
  ['NUTRICIONISTA CLINICA', 'NUTRICIONISTA CLÍNICO(A)'],
  ['NUTRICIONISTA DE PRODUCAO', 'NUTRICIONISTA DE PRODUÇÃO'],
  ['GERENTE NUTRIÇÃO PRODUÇÃO', 'GERENTE DE NUTRIÇÃO E PRODUÇÃO'],
  ['LIDER DE HIGIENE', 'LÍDER DE HIGIENE'],
  ['LIDER DE COZINHA', 'LÍDER DE COZINHA'],
  ['LIDER DE ALMOXARIFADO', 'LÍDER DE ALMOXARIFADO'],
  ['PSICOLOGO(A)', 'PSICÓLOGO(A)'],
  ['ENCARREGADO DE MANUTENCAO', 'ENCARREGADO(A) DE MANUTENÇÃO'],
  ['TECNICO DE MANUTENCAO', 'TÉCNICO(A) DE MANUTENÇÃO'],
  ['1/2 OFICIAL DE COZINHA', 'MEIO OFICIAL DE COZINHA']
];

module.exports = async function normalizarCargos(connection) {
  for (const [origem, destino] of CARGOS) {
    await connection.query(
      'UPDATE importacao_funcionarios_itens SET cargo = ? WHERE TRIM(cargo) = ?',
      [destino, origem]
    );

    const [origens] = await connection.query('SELECT id FROM cargos WHERE nome = ?', [origem]);
    if (!origens.length) continue;

    await connection.query('INSERT IGNORE INTO cargos (nome) VALUES (?)', [destino]);
    const [destinos] = await connection.query('SELECT id FROM cargos WHERE nome = ?', [destino]);
    const origemId = origens[0].id;
    const destinoId = destinos[0].id;
    if (String(origemId) === String(destinoId)) continue;

    await connection.query(
      'INSERT IGNORE INTO cargo_risco (cargo_id, risco_id) SELECT ?, risco_id FROM cargo_risco WHERE cargo_id = ?',
      [destinoId, origemId]
    );
    await connection.query(
      'INSERT IGNORE INTO cargo_exame (cargo_id, exame_id) SELECT ?, exame_id FROM cargo_exame WHERE cargo_id = ?',
      [destinoId, origemId]
    );
    await connection.query('UPDATE funcionarios SET cargo_id = ? WHERE cargo_id = ?', [destinoId, origemId]);
    await connection.query('UPDATE historico_aso SET cargo_id = ? WHERE cargo_id = ?', [destinoId, origemId]);
    await connection.query('DELETE FROM cargos WHERE id = ?', [origemId]);
  }
};
